version: 0.2

phases:
 install:
  commands:
   - echo Executing Install phase

 pre_build:
  commands:
   - echo in pre build state

 build:
  commands:
   - echo in build state
   - aws cloudformation create-stack --stack-name my-ec2-stack --template-body file://MyTestEC2YML.yml

 post_build:
  commands:
   - echo in post build state